version: '3.8'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./temp:/app/temp
      - ./static:/app/static
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: .
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - BACKEND_HOST=backend
    volumes:
      - ./temp:/app/temp
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
